{% set name = "asciidoc" %}
{% set version = "10.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 064e34241bd96e7239e8048596ceb03262d63145d04070d53906151f2042d007
  patches:
    - a2x.patch

build:
  number: 0
  skip: true  # [win or py3k]

requirements:
  host:
    - libxml2
    - libxslt
    - python
    - autoconf
  run:
    - python

test:
  source_files:
    - doc/asciidoc.txt
    - tests/**
  commands:
    - asciidoc --help
    - asciidoc doc/asciidoc.txt
    - python tests/testasciidoc.py update && python tests/testasciidoc.py run

about:
  home: https://github.com/asciidoc
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Text based document generation

  description: |
    AsciiDoc is a text document format for writing notes, documentation,
    articles, books, ebooks, slideshows, web pages, man pages and blogs.
    AsciiDoc files can be translated to many formats including HTML, PDF, EPUB,
    man page.

    AsciiDoc is highly configurable: both the AsciiDoc source file syntax and
    the backend output markups (which can be almost any type of SGML/XML markup)
     can be customized and extended by the user.
  doc_url: http://asciidoc.org/userguide.html
  dev_url: https://github.com/asciidoc/asciidoc

extra:
  recipe-maintainers:
    - carlodri
