# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Mk2a+iaAWOsyYhauapaxdalIlxMUNOZQVZkqg22+okmNaW0fYw7Kh2TZvptebzartYCsop90JweoW0kqv9YHUht677zRWJbSaxHNZ+wx9xfXUoj98EjT+YdQ5tfC5V5S4o5SWe4v3ug+sdds6p6I/i9h/LBKlzpxLUi1sRzzhe45xkdrM7CrVE48BJ8PByrSaXaFlOjKXeIXJIVnlM9IDhqib7rEkFKmSw+Ue7x3/vl3kmyvMpvq2JMGKpLJQnCd8nLcEwxpEUp7mKgIOapiN2hHgn/F7/51orAbXjoyz7vBwGD/oPZa8jbvcHCS18cZNYxZ8p5HiG0zQ8ySAgHEvgU1Qoyk/ErJQEjDFDF4BVDnRou7iOR+Kjk8k4iTLTN51XG5N144TsWz8cN4T6MwtFWGtXfTR/8A2CbZjjUbTU2mIIUFezXs5qzHaDmAAaiG43cvrbrLMfqfjLVqtvuapOYLrdmaPRyMm94kxcZ1Fjku+TYFWSeaHazyDOYjushCdafUvjUH+bcNlDZ2GURtC+jIbNzAg2E+Vqq/wmSylvkt7nV9twwtzMzs9oXHdlXJ+sBRCyef1aokzX9T56wrG21iYZqL02Wmpm1F35wev2H6tEtzfJJEBjPQrW+oLvvjll/aqfOMUwuJNtqvPfLhVeM7NneKGy4lKCxeNFSHGco="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
