travis:
  secure:
    BINSTAR_TOKEN: ANeAZXr4epLuokWpjfmOVbmavpGzZ41OXT1KcsQWIwlkN9+46fRBsrj9JWjAqtk3qvvFvsgX3tU8rU86avAc+5PfFDsYqym1HGa6BwrRZf0Y4g2zc1OX2H7nBKP3/tNagDCodi5e/PYgJkr5TdyFrOOsv88FEbLY82WH3CxMmoMb/Hu8hT10ZHtAWxPOMYDdIPSVOjv94KQkE3BiH/sY81hrQlUeUoPmoSnTTpadpo0NTttZk2pW0PNopyGcRAoMYIk2AV3bylNIsLop5GfH6maxcYM0PMcdVG7IPmv3oBnIrfb4EyUPozlnGSzDnP/pNQMTX+WjNMm3Lx5X6713aqwF3Ot7rpIgOvZRAY1u+6MoIAG5XFTfxLxL5N3fELuHo9Fi/yfkkn13v5qI2v4cMiO77auuQLGrYSJduMd2Rj3Xx+Ivo7k1x6Q7WiHPKmXjB32QeoeoYcDhEVMcbn6o14i45Gs4+mIbA/aTsEbTx7hOrcCTngqkODSUEq6EyovmsqCfJ5jimQnwpOso1pFMSRMY6MmNPr8jt9yG9NXTx2OIT7/YyxO9gAO3LMEsqaW73XJXc39FpLzzntdOMw4MwW2nPt3PS2Zw+dZj5tHemjNX+fBJgcDPKXoBAUhoVqbcktC8eE0J4UIl7cqfHhtFA0vLfPK5tslhriQNp6SoaJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
